# create your drupal and postgres config here, based off the last assignmenit

version: '2'

services:
  drupal:
    image: drupal
    ports:
      - "8090:80" 
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=deep3874
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
